# Generated by Django 4.2.16 on 2026-05-27 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField(verbose_name='Зміст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва розділу')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.section', verbose_name='Батьківський розділ')),
            ],
            options={
                'verbose_name': 'Розділ',
                'verbose_name_plural': 'Розділи',
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар до змін')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Відредаговано')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'Версія сторінки',
                'verbose_name_plural': 'Версії сторінок',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='ШІ-резюме')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='wiki.page', verbose_name='Сторінка')),
            ],
            options={
                'verbose_name': 'ШІ-резюме',
                'verbose_name_plural': 'ШІ-резюме',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='wiki.section', verbose_name='Розділ'),
        ),
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Читач'), ('editor', 'Редактор'), ('admin', 'Адміністратор')], default='viewer', max_length=20, verbose_name='Роль')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='wiki.section', verbose_name='Розділ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Право доступу',
                'verbose_name_plural': 'Права доступу',
                'unique_together': {('user', 'section')},
            },
        ),
    ]
